import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { API_BASE_URL } from '../../core/config/api-config.token';
import { ApiResponse } from '../../core/models/api-response.model';
import { Campaign, CampaignListData, CampaignRecipientListData, CampaignReport, CampaignWriteRequest } from './campaign.model';
import { CampaignService } from './campaign.service';

describe('CampaignService', () => {
  let service: CampaignService; let http: HttpTestingController;
  const campaign: Campaign = { id: 'c1', templateId: 't1', name: 'Launch', description: null, sendType: 'NOW', scheduledAt: null, status: 'DRAFT', totalRecipients: 2, sentCount: 0, deliveredCount: 0, readCount: 0, failedCount: 0, progress: 0, startedAt: null, completedAt: null, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' };
  const envelope = <T>(data: T): ApiResponse<T> => ({ success: true, message: 'ok', data });
  beforeEach(() => { TestBed.configureTestingModule({ providers: [provideHttpClient(), provideHttpClientTesting(), { provide: API_BASE_URL, useValue: '/api/v1' }] }); service = TestBed.inject(CampaignService); http = TestBed.inject(HttpTestingController); });
  afterEach(() => http.verify());

  it('lists with exact paging, sorting and filters without companyId', () => { const data: CampaignListData = { campaigns: [campaign], pagination: { page: 2, limit: 20, totalRecords: 21, totalPages: 2 } }; service.getCampaigns({ page: 2, limit: 20, sortBy: 'created_at', order: 'ASC', status: 'DRAFT', sendType: 'NOW', templateId: 't1' }).subscribe((value) => expect(value).toEqual(data)); const req = http.expectOne((r) => r.url === '/api/v1/campaigns'); expect(req.request.params.get('page')).toBe('2'); expect(req.request.params.get('sortBy')).toBe('created_at'); expect(req.request.params.get('status')).toBe('DRAFT'); expect(req.request.params.get('sendType')).toBe('NOW'); expect(req.request.params.get('templateId')).toBe('t1'); expect(req.request.params.has('companyId')).toBeFalse(); req.flush(envelope(data)); });
  it('searches with keyword', () => { service.searchCampaigns('launch').subscribe(); const req = http.expectOne('/api/v1/campaigns/search?keyword=launch'); expect(req.request.method).toBe('GET'); expect(req.request.params.get('keyword')).toBe('launch'); req.flush(envelope([campaign])); });
  it('gets campaign details and report', () => { service.getCampaign('c1').subscribe(); let req = http.expectOne('/api/v1/campaigns/c1'); req.flush(envelope(campaign)); const report = { campaignId: 'c1', campaignName: 'Launch', status: 'DRAFT', totalRecipients: 2, sentCount: 0, deliveredCount: 0, readCount: 0, failedCount: 0, progress: 0, deliveryRate: 0, readRate: 0, failureRate: 0, startedAt: null, completedAt: null } as CampaignReport; service.getCampaignReport('c1').subscribe((value) => expect(value).toEqual(report)); req = http.expectOne('/api/v1/campaigns/c1/report'); req.flush(envelope(report)); });
  it('creates and updates including an ISO schedule', () => { const payload: CampaignWriteRequest = { name: 'Launch', description: null, templateId: 't1', sendType: 'SCHEDULED', scheduledAt: '2026-09-01T10:00:00.000Z' }; service.createCampaign(payload).subscribe(); let req = http.expectOne('/api/v1/campaigns'); expect(req.request.method).toBe('POST'); expect(req.request.body.scheduledAt).toBe('2026-09-01T10:00:00.000Z'); expect(req.request.body.companyId).toBeUndefined(); req.flush(envelope(campaign)); service.updateCampaign('c1', payload).subscribe(); req = http.expectOne('/api/v1/campaigns/c1'); expect(req.request.method).toBe('PUT'); expect(req.request.body).toEqual(payload); req.flush(envelope(campaign)); });
  it('sends, cancels, and deletes with exact endpoints', () => { service.sendCampaign('c1').subscribe(); let req = http.expectOne('/api/v1/campaigns/c1/send'); expect(req.request.method).toBe('POST'); req.flush(envelope({})); service.cancelCampaign('c1').subscribe(); req = http.expectOne('/api/v1/campaigns/c1/cancel'); expect(req.request.method).toBe('POST'); req.flush(envelope({})); service.deleteCampaign('c1').subscribe(); req = http.expectOne('/api/v1/campaigns/c1'); expect(req.request.method).toBe('DELETE'); req.flush(envelope(null)); });
  it('assigns customer IDs without companyId', () => { service.assignRecipients({ campaignId: 'c1', customerIds: ['u1'] }).subscribe(); const req = http.expectOne('/api/v1/campaign-recipients/assign'); expect(req.request.method).toBe('POST'); expect(req.request.body).toEqual({ campaignId: 'c1', customerIds: ['u1'] }); expect(req.request.body.companyId).toBeUndefined(); req.flush(envelope({ message: 'ok', totalRecipients: 1 })); });
  it('gets a typed paginated recipient report', () => { const data: CampaignRecipientListData = { recipients: [], pagination: { page: 1, limit: 10, totalRecords: 0, totalPages: 0 } }; service.getCampaignRecipients({ campaignId: 'c1', page: 1, limit: 10, status: 'SENT' }).subscribe((value) => expect(value).toEqual(data)); const req = http.expectOne((r) => r.url === '/api/v1/campaign-recipients'); expect(req.request.params.get('campaignId')).toBe('c1'); expect(req.request.params.get('status')).toBe('SENT'); req.flush(envelope(data)); });
  it('propagates API errors', () => { let status = 0; service.getCampaigns().subscribe({ error: (error) => status = error.status }); http.expectOne('/api/v1/campaigns').flush({ success: false, message: 'Forbidden', errors: null }, { status: 403, statusText: 'Forbidden' }); expect(status).toBe(403); });
});
