const SUBSCRIPTION_STATUSES = Object.freeze({
  TRIALING: "TRIALING",
  ACTIVE: "ACTIVE",
  PAST_DUE: "PAST_DUE",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
});

const SUBSCRIPTION_ACTIONS = Object.freeze({
  CREATED: "CREATED",
  ACTIVATED: "ACTIVATED",
  TRIAL_STARTED: "TRIAL_STARTED",
  PLAN_CHANGED: "PLAN_CHANGED",
  UPGRADED: "UPGRADED",
  DOWNGRADED: "DOWNGRADED",
  DOWNGRADE_SCHEDULED: "DOWNGRADE_SCHEDULED",
  DOWNGRADE_CANCELLED: "DOWNGRADE_CANCELLED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  RENEWED: "RENEWED",
});

const SUBSCRIPTION_SOURCES = Object.freeze({
  ADMIN: "ADMIN",
  SYSTEM: "SYSTEM",
  PAYMENT: "PAYMENT",
});

const SUBSCRIPTION_DEFAULTS = Object.freeze({
  TRIAL_DAYS: 14,
  PERIOD_DAYS: 30,
});

module.exports = {
  SUBSCRIPTION_STATUSES,
  SUBSCRIPTION_ACTIONS,
  SUBSCRIPTION_SOURCES,
  SUBSCRIPTION_DEFAULTS,
};
